# Generated by Django 3.2.5 on 2022-06-15 10:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_me', '0003_remove_skilltranslation_skill_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='project_image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.profile')),
                ('stack', models.ManyToManyField(blank=True, to='projects.Stack')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='Mainproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, upload_to='project_cover')),
                ('image', models.ImageField(blank=True, upload_to='project_image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.profile')),
                ('stack', models.ManyToManyField(blank=True, to='projects.Stack')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='StackTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('stack', models.CharField(max_length=96)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.stack')),
            ],
            options={
                'verbose_name': 'stack Translation',
                'db_table': 'projects_stack_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='ProjectsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('project_name', models.CharField(max_length=255)),
                ('project_shortdescription', models.CharField(blank=True, max_length=2550)),
                ('skill_fulldescription', models.TextField(blank=True, max_length=25500)),
                ('github_link', models.CharField(blank=True, max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.projects')),
            ],
            options={
                'verbose_name': 'projects Translation',
                'db_table': 'projects_projects_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='MainprojectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('project_name', models.CharField(max_length=255)),
                ('project_shortdescription', models.CharField(blank=True, max_length=2550)),
                ('skill_fulldescription', models.TextField(blank=True, max_length=25500)),
                ('github_link', models.CharField(blank=True, max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.mainproject')),
            ],
            options={
                'verbose_name': 'mainproject Translation',
                'db_table': 'projects_mainproject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel,),
        ),
    ]
