# Generated by Django 3.2.5 on 2022-06-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproject',
            options={'verbose_name': 'Mainproject', 'verbose_name_plural': 'Mainprojects'},
        ),
        migrations.AlterModelOptions(
            name='mainprojecttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Mainproject Translation'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Project Translation'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'Stack', 'verbose_name_plural': 'Stack'},
        ),
        migrations.AlterModelOptions(
            name='stacktranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Stack Translation'},
        ),
        migrations.RenameField(
            model_name='mainprojecttranslation',
            old_name='skill_fulldescription',
            new_name='project_fulldescription',
        ),
        migrations.RenameField(
            model_name='projectstranslation',
            old_name='skill_fulldescription',
            new_name='project_fulldescription',
        ),
    ]
