# Generated by Django 3.2.5 on 2022-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220615_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprojecttranslation',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectstranslation',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
