# Generated by Django 4.0.4 on 2022-11-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220615_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainprojectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project_image')),
                ('alt_pl', models.CharField(blank=True, max_length=255)),
                ('alt_en', models.CharField(blank=True, max_length=255)),
                ('main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mainproject')),
            ],
        ),
    ]
