# Generated by Django 4.0.4 on 2022-06-13 18:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profile/user.png', upload_to='profile')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Short',
            },
            bases=(parler.models.TranslatableModel,),
        ),
        migrations.CreateModel(
            name='ShortdescriptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('up_text', models.CharField(max_length=255)),
                ('down_text', models.CharField(max_length=255)),
                ('fb_link', models.CharField(blank=True, max_length=255)),
                ('github_link', models.CharField(blank=True, max_length=255)),
                ('linkedin_link', models.CharField(blank=True, max_length=255)),
                ('instagram_link', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about_me.shortdescription')),
            ],
            options={
                'verbose_name': 'Short Translation',
                'db_table': 'about_me_shortdescription_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel,),
        ),
    ]
