# Generated by Django 4.0.4 on 2022-06-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_profile_skill_mainskill_shortdescription_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltranslation',
            name='skill_description',
        ),
        migrations.AlterField(
            model_name='skilltranslation',
            name='skill_name',
            field=models.CharField(max_length=255),
        ),
    ]
