# Generated by Django 4.0.4 on 2022-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_alter_profiletranslation_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletranslation',
            name='contact_me_down',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profiletranslation',
            name='contact_me_up',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
