# Generated by Django 4.0.4 on 2022-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_alter_message_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='profile',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
