# Generated by Django 4.0.4 on 2022-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0008_rename_profile_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletranslation',
            name='full_text',
            field=models.TextField(max_length=25500),
        ),
    ]
