# Generated by Django 4.0.4 on 2022-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0009_alter_profiletranslation_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainskilltranslation',
            name='skill_description',
            field=models.TextField(max_length=2550),
        ),
    ]
