# Generated by Django 4.0.4 on 2022-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220610_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(default='defoult.png', upload_to='post_cover'),
        ),
    ]
