# Generated by Django 4.0.4 on 2022-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_image'),
        ),
    ]
