# Generated by Django 4.0.4 on 2022-06-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postimages_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
