# Generated by Django 4.0.4 on 2022-07-09 14:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000),
        ),
    ]
