# Generated by Django 4.0.4 on 2022-07-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogposttranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='opis',
            field=models.TextField(blank=True),
        ),
    ]
