# Generated by Django 4.0.4 on 2022-07-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttranslation',
            name='opis2',
            field=models.TextField(blank=True),
        ),
    ]
